apiVersion: v1
kind: Service

# Metadate for name of the service
metadata:
  name: nginx-svc
  namespace: default # sre
spec:
  ports:
  - nodePort: 30001
    port: 80
    targetPort: 80

  selector:
    app: nginx
  
  type: NodePort
