apiVersion: apps/v1
kind: Deployment # What kind of service you want to cerate

metadata:
  name: nginx-deployment #naming the deployment
spec:
  selector:
    matchLabels:
      app: nginx # look for this label to match with k8 service
  
  # Replica set for this with pods/instances
  replicas: 3
  # template to use it's label for K8 services to launch in the browesr
  template:
    metadata:
      labels:
        app: nginx # This label connects to the service or any other k8 services
    # Container specs
    spec:
      containers:
      - name: nginx
        image: abishek726/new-node-app:latest # Use this image from docker hub
        ports:
        - containerPort: 80